### PR TITLE
added a cmake and instructiosn on how to get API KEY

### PR DESCRIPTION
**Pull request by velocitatem**
This pull request includes several important changes to the build configuration, documentation, and platform-specific includes. The most important changes are listed below:

### Build Configuration:

* [`CMakeLists.txt`](diffhunk://#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR1-R27): Added a new CMake configuration file to set up the project with C++17 standard, include necessary libraries (`nlohmann_json`, `CURL`, `SFML`), and specify the source files and include directories.

### Documentation:

* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R57-R62): Added instructions to obtain a NASA API key and set it up in a `.env` file.

### Platform-Specific Includes:

* [`src/platform_config.h`](diffhunk://#diff-ccd4394cd5fba555a729bafbe1b8c160d0690e178320e5fec870186747364443L10-R13): Updated the include paths for `nlohmann/json.hpp` to use the correct library path for each platform (Windows, macOS, Linux).

### CODE REVIEW

**Review by GRINGOLOCO7 — COMMENTED** [review]
for conditional compilation (src/platform_config.h) our group member with mac, downloaded the library localy... that is why we used conditional compilation. They do need the comands as you founded them:

```
#elif defined(__APPLE__) || defined(__MACH__)
    #include <nlohmann/json.hpp>
    #define OS_NAME "macOS"
```
So I would deleate your changes if u don't mind.

for the rest, I would love to merge after @Torkuno  agrees. Could you also add on readme how to compile and use your CMake?

**Comment by velocitatem** [comment]
Its just my recommendation since hard-coding the library source code is not a very good practice and CMake can fix that. The binary can be accessed on a mac with the following if necessary: https://formulae.brew.sh/formula/nlohmann-json

Whichever decision you make its ok with me.

**Comment by Matzmuda4** [comment]
Oh okay thanks for Clarifying @velocitatem I agreed with Gringo on this note but I do agree that hard-coding the library source code a bad practice,  and I love the changes you've implemented they're extremely useful and I would agree for a merge, just need @Leesanchez and @Torkuno to review and see if they agree.

**Comment by velocitatem** [comment]
Ok nice, lmk if it runs on everyone's computers all good 👍🏻

**Comment by Torkuno** [comment]
I am currently facing issues with this CMake configuration.
My system is unsuccessfully trying to find Zlib.
I've tried uninstalling and reinstalling the files repeatedly.
I've also tried running on Windows PowerShell and Ubuntu WLS.

I would really like to know if it runs for @GRINGOLOCO7 to see if it's a reoccurring problem or specific to my system.

**Pull request merged**
